// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyixstdknvremrjvaarx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5aXhzdGRrbnZyZW1yanZhYXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTIyMDUsImV4cCI6MjA1NzUyODIwNX0.Y7-jy7P8iqSSVaTxkHnNc06W0iemUCvDGUdnutnA1sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);